import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import API from 'service/api';
import Image from 'next/image';

export default function Home({ data }) {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    const { results } = data;
    console.log(results);
    setMovies(results || []);
  }, []);

  return (
    <>
      <Head>
        <title>home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        {movies.map((item: any) => (
          <>
            <article className="mb-3" key={item.id}>
              <Image src={`http://image.tmdb.org/t/p/w500/${item.poster_path}`} alt="영화이미지" width={500} height={500} />
              <div>{item.title}</div>
            </article>
          </>
        ))}
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const res: any = await API.movie.getMovies();

  return {
    props: {
      data: res.data,
      // name: process.env.name,
    },
  };
}
