import React, { useEffect } from 'react';
import Head from 'next/head';
import App from './_app';
import API from 'service/api';

export default function Home({ data }: any) {
  // const getNews = async () => {
  //   await API.news
  //     .getNaverNews()
  //     .then((res) => {
  //       console.log(res);
  //     })
  //     .catch((e) => {
  //       console.log(e);
  //     });
  // };

  useEffect(() => {
    console.log(data);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        {data.items.map((item: any) => (
          <>
            <article className="mb-3">
              <div>{item.title}</div>
              <div>{item.description}</div>
            </article>
          </>
        ))}
      </section>
    </>
  );
}

export async function getServerSideProps() {
  const res: any = await API.news.getNaverNews();
  return {
    props: {
      data: res.data,
      // name: process.env.name,
    },
  };
}
