import React, { useEffect } from 'react';
import Head from 'next/head';
import App from './_app';
import API from 'service/api';

export default function Home() {
  const getNews = async () => {
    await API.news
      .getNaverNews()
      .then((res) => {
        console.log(res);
      })
      .catch((e) => {
        console.log(e);
      });
  };

  useEffect(() => {
    getNews();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <App /> */}ss
    </>
  );
}

// export async function getStaticProps() {
//   // const apiUrl = process.env.apiUrl;
//   const res = await API.news.getNaverNews();
//   // const data = res.data;

//   console.log(res);
//   return {
//     props: {
//       list: data,
//       name: process.env.name,
//     },
//   };
// }
